---
sudo: required

env:
  - distribution: centos
    version: 7


services:
  - docker


before_install:
  - 'sudo docker pull ${distribution}:${version}'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/rppf/ansible-stack/roles/php7:ro ${distribution}-${version}:ansible > "${container_id}"'
  # Syntax Check
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /rppf/ansible-stack/tests/test.yml --syntax-check'
  # Test role
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /rppf/ansible-stack/tests/test.yml'

after_sucess:
  - 'sudo docker stop "$(cat ${container_id})"'
