---
sudo: required
group: deprecated-2017Q4

env:
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opt: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

services:
  - docker

before_install:
  - 'sudo docker pull geerlingguy/docker-${distro}-ansible:latest'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --volume="${PWD}":/rppf/ansible-stack/roles/php7:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'
  # Syntax Check
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /rppf/ansible-stack/tests/test.yml --syntax-check'
  # Test role
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /rppf/ansible-stack/tests/test.yml'

after_sucess:
  - 'sudo docker stop "$(cat ${container_id})"'
