---
- name: Download Nodejs
  get_url:
    url: https://rpm.nodesource.com/setup_8.x
    dest: /tmp

- name: Setup Nodejs
  shell: bash - /tmp/setup_8.x

- name: Install Nodejs
  apt:
    pkg: nodejs
    state: latest

- name: Install Yarn using npm
  npm:
    name: yarn
    global: yes
