---
- name: Add MariaDB key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 1BB943DB

- name: Add MariaDB repo to apt repo path
  template:
    src: MariaDB.list
    dest: /etc/apt/sources.list.d

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MariaDB
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - mariadb-server
    - mariadb-client
    - python-mysqldb
