---
- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: yes
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: absent
  tags: mariadb

- name: Create the users
  mysql_user:
    name: '{{ database_user }}'
    password: '{{ database_password }}'
    host: localhost
    priv: '{{ database_name }}.*:ALL'
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
  tags: mariadb
